# Generated by Django 3.1.3 on 2020-11-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sb_app', '0003_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('details', models.JSONField(default=dict)),
            ],
        ),
    ]
